### ISSUE TITLE
Cannot deploy example guestbook

### ISSUE THREAD

**Issue by adamreese** [kubernetes/deployment-manager#183]
When following example from Readme

```
$ dm deploy ./examples/guestbook/guestbook.yaml
2016/01/25 18:03:14 cannot get URLs for ./examples: cannot list versions at path examples/: GET https://api.github.com/repositories/46806184/contents/examples: 404 Not Found []
```

**Comment by vaikas-google** [comment]
So there's two problems here:
 1. the dm client is for some reason assuming that this is a type instead of a file
    - This looks to have been introduced some CLs ago when the dm client was refactored to handle direct types / stdin or something like that. I'll fix that shortly (I hacked it to test the theory)
 2. k8s now requires the nodeport when creating a service

This is what I see in the logs with my hack mentioned above.

2016/01/25 21:36:34 manager: create deployment: returning response: status code:400, status:Found resource errors during deployment: [kubectl failed for resource: frontend-service: exit status 1: error validating "STDIN": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false
 kubectl failed for resource: redis-master: exit status 1: error validating "STDIN": error validating data: field nodePort: is required; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by vaikas-google** [comment]
This should've been fixed by now.
