### ISSUE TITLE
expandybird/manager/resourcifier all with their own RC

### ISSUE THREAD

**Issue by runseb** [kubernetes/deployment-manager#269]
Is it intended for exapndybird, manager and resourcifier to have their own RC or could they exist in a the same pod ?

**Comment by jackgr** [comment]
They need to run independently, when the service runs at scale, for the following reasons:
* expandybird does python based expansion, and will be sand boxed at some point.
* resourcifier runs kubectl and may be slow, if the cluster takes time spinning up resources.

Given that we're still early on, it shouldn't be a problem to run them all in the same rc, and to remove the services for expandybird and resourcifier. Note, however, that you'll need to pass the localhost addresses of these two containers to manager, since it won't be able to find them on DNS anymore.

**Comment by runseb** [comment]
ok thanks for the clarification. Makes sense.
Closing this.
