### ISSUE TITLE
Docker images are too big

### ISSUE THREAD

**Issue by runseb** [kubernetes/deployment-manager#270]
docker images for expandybird and co are really big 600MB to 700MB+

We should consider using alpine or other alternatives to make these images smaller

**Comment by michelleN** [comment]
I agree. We could compile the component outside of the container (` CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ${BIN_NAME}`) and ADD the binary to it. Of course, we don't have to do it that way.
Regardless, these images could be 15MB instead of 600-700MB.

These are related threads on the matter:
1. https://www.brianchristner.io/docker-is-moving-to-alpine-linux/
2. https://news.ycombinator.com/item?id=10998667
3. http://carlosbecker.com/posts/small-go-apps-containers

@runseb do you have any recommendations here?

**Comment by runseb** [comment]
for the resourcifier we can easily switch to Alpine. I will submit a PR for this.

For the go binaries, I haven't looked deeply into it but we could use a 'scratch' base image and do what you say.

**Comment by technosophos** [comment]
Should we mark this as closed now, since we have Alpine as the image in the merged repo?

**Comment by runseb** [comment]
We can, yes just checked the Dockerfile but haven't checked the actual size of the image.

**Comment by michelleN** [comment]
Alrighty. Closing this for now and will re-open an issue if this an issue for helm moving forward.
