### ISSUE TITLE
Helm Team Dev Process Proposal

### ISSUE THREAD

**Issue by michelleN** [kubernetes/deployment-manager#319]
Below is an outline of how the Helm/Deis team (www.github.com/helm/helm) goes about development process. I'd love to see a similar process for this new merged helm/dm project. With the process below, we saw a number of community contributions, little process overhead, and high velocity.

# The Helm Dev Process

- ​The Deis/Helm team uses a Kanban-style development cycle.
- We don't do discrete sprints.
- People self-assign tasks
- Tasks are done in priority order (meaning if they are priority for the next release)
- We have a release target (in the form of a milestone) that includes features we want and fixes we need, and we collectively work toward it.
- The release of one target and the planning for the next happen at the same time
- We use standups to synchronize
- The only formal process tool that we use is the GitHub issue queue. 
- The Team Leader's job is just to coordinate, keep track of things, and point out when things are falling through the cracks. 
​

Since we work this way, we don't really prioritize issues. For us, issues are either "P1" (needs to be done for the release) or "P3" (not gonna even discuss until after the release). On occasion, we hit something really high in importance, and will run that up the queue above all else. 

In the issue queue:
- We use a red "bug" label to convey an issue is a bug.
- Instead of the "P0" label, we use a red "showstopper" label 
- We use a blue "proposal" tag to submit new features or architecture changes for discussion.
- We use a blue "enhancement" label to identify any enhancement suggestions. 

This an open source project so we want to empower the community to be able to see, understand, and contribute to clearly what we're working on. _Unambiguous labels_ on issues and PRs help project so we want to empower the community to be able to see and understand clearly what we're working on. 

I'd like to also follow this pattern for a monthly release cadence similar to Deis v1's pattern. 
1. Cut a release the first Monday of every month
2. Hold a ** public community release planning meeting** the following Wedneday after a release. This meeting includes a status update from the team and an update of the upcoming priorities for the next release. It's a place for the community to communicate with the core team and share their experiences. It's also a forum for the community to make requests.
_See the [Deis Planning Process](http://docs.deis.io/en/latest/roadmap/planning/#planning) for more details on the Deis process. Note: I'm not suggesting we use all of it. Just a place to draw insipiration from._

Please let me know if this works for everyone or if you have any outstanding concerns. I want to make sure there is team consensus before moving forward with this process.

cc/ @adamreese @technosophos @jackgr @bmelville @vaikas-google @sparkprime @runseb

**Comment by sgoings** [comment]
Of note... the **1. Cut a release the first Monday of every month** line should allude to a process which strives to make releases non-heroic, no-changes-needed, normal events. This naturally happens when the project has a fully automated delivery system which can rely on a quality gate of automated testing.

With helm we had built up a nice ability to just add a `git tag` or initiate a github release action (which under the hood creates a git tag as well). I'd hate to give up that lifestyle. :wink:

That being said, I'd like to help make this a reality where/when I can.

**Comment by michelleN** [comment]
haha oh automated releases based on reliable automated testing is always the dream @sgoings. Im in for movinf towards initiating a github release action to do all of the things necessary for releasing. Do you think we should tackle as a goal for the MVP release or should we just work towards that as we will?

**Comment by jackgr** [comment]
Lots to digest there. However, our intent is largely aligned with what you've laid out, except that we do use sprints.

The goal of using sprints is to take regular check points, which helps prevent the problem of getting to a release only to find that things aren't running as expected. Sprints don't have to be heavyweight. They're just a checkpointing mechanism. 

We allocate issues to sprints so that we have a sense of what we think makes sense to accomplish in the time period, but if an issue isn't completed by the sprint boundary. it's not a problem... we merely push it to the next sprint. Github keeps track of the movement, and if an issue doesn't land in a timely manner, that's easy to see.

We allocate PRs to sprints to see what we got done.

This mechanism makes it easy to filter and ask questions, such as:
* What did we do while bmelville was away?
* What are we focusing on this sprint?

As I see it, our sprints are like your releases, except that sprints are finer grained, creating more frequent checkpoints. Also, your releases carry a lot of overhead, as releases should, and I don't just mean the community meeting, there's also the label and the need for customers to track/align with them. 

In other words, there's a trade-off here between release overhead and release frequency, and some of the benefit can be realized with less overhead. For example, Kubernetes has a weekly community meeting, and infrequent releases.

Personally, I'm more comfortable with finer grained checkpoints and less frequent releases, with multiple checkpoints per release.

All of the rest of your first set of bullets are the same for us.

Not sure I understand what you meant by:

> Since we work the current DM way, we don't really prioritize issues. For us, issues are either "P1" (needs to be done for the release) or "P3" (not gonna even discuss until after the release). On occasion, we hit something really high in importance, and will run that up the queue above all else.

We use the Kubernetes labels, including the priority labels they've defined. They work well for that community, which overlaps heavily with our community, so most collaborators are familiar with them, and we've had no problems with them.

We also use the Kubernetes bug and lgtm labels. We occasionally use other labels, such as the helm label for everything related to the helm integration. 

Personally, I like using the area and components labels for things that need to be flagged at a point in time as relevant to work in a particular area, such as the api work currently underway, or the set of client commands now under development, because they make it easy to filter and ask questions, such as:

* What are all the issues related to cleaning up the APIs?
* What are all the issues related to building out the client commands?

However, if they give anyone heartburn, I can certainly live without them, and read through the issues one by one to get my answers. :0)

**Comment by jackgr** [comment]
One more thing to note is that when people self-assign, they set the Assignee field to themselves. It's also common in our world for us to assign work to each other, if it's in that person's area. For example, if there's an issue related to something that @vaikas-google is working on, I'll assign it to him and vice versa. Kubernetes works the same way.

**Comment by vaikas-google** [comment]
I too would rather see more granular 'checkpoints' than a month. If they are in the form of sprints, which is what we've been using great, if something else, great. The goal should simply be able to detect slips / problems earlier rather than later.

**Comment by jackgr** [comment]
I'm not sure where we discussed the # of LGTMs, but I'm starting to see the wisdom of @michelleN's comments on this subject.

With just 1 LGTM, it's too easy for PRs to be LGTM'ed by someone working closely with the submitter, without involving other potential stakeholders. 2 LGTMs would help solve that problem.

Another way to solve the problem and keep things lightweight, would be to require at least one LGTM from someone working on a different area of the product. So for example, every PR against the server would need at least one LGTM from someone working on the client and vice versa.

**Comment by jackgr** [comment]
So, we probably need to be a bit more clear about self assignment of tasks. Today, we had a collision between #316 and #323, both addressing #292. The collision could have been avoided by interpreting the assignment field as meaning "the person named here is responsible for fixing this issue".

In other words, self assignments of tasks only works if we use the Assignee field to record assignment, and then work on only those things to which we are assigned.

Make sense?

**Comment by michelleN** [comment]
Closing this since we have #346 merged.
