### ISSUE TITLE
Remove travis if CircleCI works well for us

### ISSUE THREAD

**Issue by michelleN** [kubernetes/deployment-manager#334]

**Comment by michelleN** [comment]
We'll still need to remove the travis hook from this project. @jackgr - I don't have access to the settings page. I would expect to see it with admin rights but it's not available for me.  Could you or @vaikas-google take care of removing that?

**Comment by michelleN** [comment]
@jackgr I see the issue with the admin rights for the deployment-manager-admins. There is not repository associated with the team. https://github.com/orgs/kubernetes/teams/deployment-manager-admins

**Comment by jackgr** [comment]
Ah. Thanks for catching that. Will fix ASAP.

On Friday, March 4, 2016, Michelle Noorali <notifications@github.com> wrote:

> @jackgr <https://github.com/jackgr> I see the issue with the admin rights
> for the deployment-manager-admins. There is not repository associated with
> the team.
> https://github.com/orgs/kubernetes/teams/deployment-manager-admins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/deployment-manager/issues/334#issuecomment-192535748>
> .
>


-- 
Jack Greenfield | Google

**Comment by michelleN** [comment]
:+1:

**Comment by jackgr** [comment]
Done.

**Comment by sgoings** [comment]
Looks like on the TravisCI side the job is still enabled (which I think will try recreating hooks?). @jackgr - could you flip that slider in TravisCI to the "off" position for deployment-manager?

![travis-ci-config](https://cloud.githubusercontent.com/assets/123755/13549195/c47db9cc-e2bd-11e5-8d79-9549c70f0f12.PNG)

**Comment by jackgr** [comment]
@sgoings Done.

**Comment by jackgr** [comment]
@michelleN thanks for catching that the admins team wasn't configured.

I got to wondering how that could have happened... so, get this...

I knew that if you create a team through `Teams` tab in the `kubernetes` organization page, you have to set the repositories it applies to and the rights it has on them.

So, instead of going that route, I went to the `Collaborators & teams` tab in the `Settings` page for the `kubernetes/deployment-manager` repo, hoping it would auto populate some parameters for me, and clicked the button to `Create a new team`.

Sure enough, it prompted me for the rights it should have, and I chose `Admin` It then created a team with the automatically generated name `deployment-manager-admins`. You'd think it would also have added `kubernetes/deployment-manager` to the repositories and would have set the rights to `Admin`, but no, it didn't.

Apparently, it only uses the parameters to generate the name.
