### ISSUE TITLE
Cannot delete deployment when resources cannot be found

### ISSUE THREAD

**Issue by LeendersR** [kubernetes/deployment-manager#70]
When you try to delete a deployment but it cannot find certain resources the deployment is not deleted.

**To reproduce**:
Deploy the Guestbook example:
`dm deploy guestbook.yaml`
Manually delete a replication controller:
`kubectl delete rc frontend-rc`
Now try to delete the Guestbook deployment
`dm delete guestbook.yaml`
This returns an error:
`cannot delete configuration: kubetcl failed for resource: frontend-rc: exit status 1: Error from server: error when stopping "STDIN": replicationControllers "frontend-rc" not found`
And deployment manager still contains the guestbook.yaml deployment:
`dm list`
includes guestbook.yaml

**Comment by bmelville** [comment]
Since we're using kubectl instead of a RESTful API, we should go for idempotency: treat these as we would a 404 on delete and call it success.

**Comment by vaikas-google** [comment]
Ideally we'd be using the API instead of kubectl so we can actually look at the response and see what the error is. Short term fix would be to parse the output and use that. If I crank up the log level higher I can actually get the API output, so in theory I could even parse that. That might be a way to get closer to using the API. I'll dig a bit deeper and figure out which way to proceed.
