### ISSUE TITLE
Create namespaces on the fly in expansions

### ISSUE THREAD

**Issue by goltermann** [kubernetes/deployment-manager#92]
If you want to deploy your resources in a namespace, you must first create it.

If you're using a template (say examples/bootstrap/bootstrap.yaml), and put a namespace in the properties, your dm deploy will actually fail if you haven't created that namespace first.

Ideally, we need the expansion to somehow do "if specified namespace doesn't exist, create it".

**Comment by bmelville** [comment]
Since namespace is just another resource, we should really keep to the current model.

What is the common usage here?

1) create namespaces on the fly as part of a micro-service deployment, or
2) have a known set of namespaces managed separately and deploy micro-services into those?

Currently (1) is broken as you say, until references are fully implemented. Once we have references, it is easy to have a deployment with a namespace resource and other resources reference it for their namespace properties.

(2) seems more appropriate but I may not fully understand the use-case of (1).

**Comment by jackgr** [comment]
Would a micro service create a namespace in the typical case, or would it just use an existing one? We need to better understand the use cases here.

**Comment by goltermann** [comment]
Thinking back on this, I can see both usecases, but I do imagine it's more common to have some "cluster admin" to have done the namespace provisioning ahead of time (case 2 above).

Case 1 is probably more common for testing or development clusters - if you deploy more than 1-2 apps through deployment manager, 'kubectl get po' quickly becomes unwieldy.

**Comment by jackgr** [comment]
Seems like case 1 is the only one that requires code change, and it should be resolved by references, per the comment from @bmelville above, so I'm closing this issue. Please feel free to reopen if that's not a valid conclusion.

**Comment by goltermann** [comment]
Agree that we can close this one.
